# Generated by Django 3.2.19 on 2023-07-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230705_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
    ]
